### ISSUE TITLE
No output for app.js

### ISSUE THREAD

**Issue by TheaterMan72** [bbtinkerer/AlexaLirc#1]
when I run node app.js I don't get the subscribed lines you discussed in the instructions.
Is there a log I can check or anything I can triple check to see if I missed something?
I've looked at the default.json and cut and pasted the IOT host from the Amazon IOT so that is correct.
I've purposefully inserted an error in default.json to see if app.js is reading it, and app.js quits and give me an error, so I know its reading the json file.
Any help I can get would be greatly appreciated

**Comment by bbtinkerer** [comment]
Wow, I don't recall seeing an email from GitHub for this. No output to the terminal, check your AWS IoT thing's policy for a misconfiguration. Thanks to Instructables member JamesG368 from for informing me of this.
